package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAuctionByAuctionIDParams creates a new AuctionByAuctionIDParams object
// with the default values initialized.
func NewAuctionByAuctionIDParams() AuctionByAuctionIDParams {
	var ()
	return AuctionByAuctionIDParams{}
}

// AuctionByAuctionIDParams contains all the bound params for the auction by auction Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters auctionByAuctionId
type AuctionByAuctionIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*the auctionId of an Auction
	  Required: true
	  In: path
	*/
	AuctionID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *AuctionByAuctionIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rAuctionID, rhkAuctionID, _ := route.Params.GetOK("auctionId")
	if err := o.bindAuctionID(rAuctionID, rhkAuctionID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AuctionByAuctionIDParams) bindAuctionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.AuctionID = raw

	return nil
}
