package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mattcollinge/auction/models"
)

// AuctionByAuctionIDOKCode is the HTTP code returned for type AuctionByAuctionIDOK
const AuctionByAuctionIDOKCode int = 200

/*AuctionByAuctionIDOK Success

swagger:response auctionByAuctionIdOK
*/
type AuctionByAuctionIDOK struct {

	/*
	  In: Body
	*/
	Payload models.AuctionResponse `json:"body,omitempty"`
}

// NewAuctionByAuctionIDOK creates AuctionByAuctionIDOK with default headers values
func NewAuctionByAuctionIDOK() *AuctionByAuctionIDOK {
	return &AuctionByAuctionIDOK{}
}

// WithPayload adds the payload to the auction by auction Id o k response
func (o *AuctionByAuctionIDOK) WithPayload(payload models.AuctionResponse) *AuctionByAuctionIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auction by auction Id o k response
func (o *AuctionByAuctionIDOK) SetPayload(payload models.AuctionResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuctionByAuctionIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.AuctionResponse, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// AuctionByAuctionIDBadRequestCode is the HTTP code returned for type AuctionByAuctionIDBadRequest
const AuctionByAuctionIDBadRequestCode int = 400

/*AuctionByAuctionIDBadRequest Bad Request

swagger:response auctionByAuctionIdBadRequest
*/
type AuctionByAuctionIDBadRequest struct {
}

// NewAuctionByAuctionIDBadRequest creates AuctionByAuctionIDBadRequest with default headers values
func NewAuctionByAuctionIDBadRequest() *AuctionByAuctionIDBadRequest {
	return &AuctionByAuctionIDBadRequest{}
}

// WriteResponse to the client
func (o *AuctionByAuctionIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// AuctionByAuctionIDUnauthorizedCode is the HTTP code returned for type AuctionByAuctionIDUnauthorized
const AuctionByAuctionIDUnauthorizedCode int = 401

/*AuctionByAuctionIDUnauthorized Unauthorised

swagger:response auctionByAuctionIdUnauthorized
*/
type AuctionByAuctionIDUnauthorized struct {
}

// NewAuctionByAuctionIDUnauthorized creates AuctionByAuctionIDUnauthorized with default headers values
func NewAuctionByAuctionIDUnauthorized() *AuctionByAuctionIDUnauthorized {
	return &AuctionByAuctionIDUnauthorized{}
}

// WriteResponse to the client
func (o *AuctionByAuctionIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
}

// AuctionByAuctionIDNotFoundCode is the HTTP code returned for type AuctionByAuctionIDNotFound
const AuctionByAuctionIDNotFoundCode int = 404

/*AuctionByAuctionIDNotFound No Auction Found

swagger:response auctionByAuctionIdNotFound
*/
type AuctionByAuctionIDNotFound struct {
}

// NewAuctionByAuctionIDNotFound creates AuctionByAuctionIDNotFound with default headers values
func NewAuctionByAuctionIDNotFound() *AuctionByAuctionIDNotFound {
	return &AuctionByAuctionIDNotFound{}
}

// WriteResponse to the client
func (o *AuctionByAuctionIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}

/*AuctionByAuctionIDDefault Unexpected Error

swagger:response auctionByAuctionIdDefault
*/
type AuctionByAuctionIDDefault struct {
	_statusCode int
}

// NewAuctionByAuctionIDDefault creates AuctionByAuctionIDDefault with default headers values
func NewAuctionByAuctionIDDefault(code int) *AuctionByAuctionIDDefault {
	if code <= 0 {
		code = 500
	}

	return &AuctionByAuctionIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the auction by auction Id default response
func (o *AuctionByAuctionIDDefault) WithStatusCode(code int) *AuctionByAuctionIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the auction by auction Id default response
func (o *AuctionByAuctionIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *AuctionByAuctionIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
}
