package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// PongModel The result of a private ping healthcheck request
// swagger:model PongModel
type PongModel string

// Validate validates this pong model
func (m PongModel) Validate(formats strfmt.Registry) error {
	return nil
}
